"""added fk

Revision ID: 02212336faf8
Revises: c7c1d29bafad
Create Date: 2023-03-20 11:12:01.467068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02212336faf8'
down_revision = 'c7c1d29bafad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_post_poster_id_users'), 'users', ['poster_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_post_poster_id_users'), type_='foreignkey')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###
