"""changed username to be unique

Revision ID: 698a452727de
Revises: 1106dc8f37b9
Create Date: 2023-03-20 00:54:58.084878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698a452727de'
down_revision = '1106dc8f37b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
